name: Docker Image Test

docker login

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Pull image from Docker Hub
        run: docker pull zthole/text_analyzer:latest

      - name: Run container tests
        run: docker run zthole/text_analyzer:latest
